resource "random_pet" "my-pet" {

  length    = var.length
}

output "pet-name" {

        value = random_pet.my-pet.id
        description = "Record the value of pet ID generated by the random_pet resource"
}
